[package]
name = "rust-stdlib"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
# https://doc.rust-lang.org/reference/linkage.html#linkage
crate-type = ["staticlib"]

[dependencies]
ocaml = { version = "0.22.4" }
